# Use this docker-compose.yaml to run a PostgreSQL server in Docker
version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: exampledb
    ports:
      - "5432:5432"

    volumes:
      - /mnt/storage/postgresql:/var/lib/postgresql/data
