version: '3.2'

volumes:
  portainer-data:
    driver: local
    
services:
  agent:
    container_name: agent
    image: portainer/agent:2.6.3
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
  app:
    container_name: portainer
    image: 'portainer/portainer-ce:latest'
    ports:
      - '9000:9000'
      - '9443:9443'
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
