version: '3.2'

volumes:
  portainer-data:
    driver: local
    
services:
  portainer-agent:
    container_name: portainer-agent
    image: portainer/agent:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - "9001:9001"
  portainer:
    container_name: portainer
    image: 'portainer/portainer-ce:latest'
    ports:
      - '9000:9000'
      - '9443:9443'
      - '8000:8000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data