version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=roman
      - MONGO_INITDB_ROOT_PASSWORD=secret
  backend:
    build: ./backend
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs # write data inside container
      - ./backend:/app # bind mounts( map code inside the container)
      - /app/node_moudels #  anonymous values
    container_name: backend
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    container_name: frontend
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
   data:
   logs: