[http.routers.traefik-api]
rule = "Host(`magahome.cloudtorq.io`)"
service = "api@internal"
middlewares = ["auth"]
[http.routers.traefik-api.tls]
certresolver = "letsencrypttls"
[http.middlewares.auth.basicAuth]
# TODO Add your admin user & password here, generate e.g. using https://wtools.io/generate-htpasswd-online
users = [
  "gknowd:$apr1$65xGsO4Q$r/ZdzgOEHBpkmg2QBE7ko/",
]