version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redis
    command: redis-server --loglevel warning
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - /mnt/storage/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s