services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto_broker
    ports:
      - "1883:1883"  # MQTT
      - "9001:9001"  # WebSocket (if needed)
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    networks:
      - mqtt_network

networks:
  mqtt_network:
    driver: bridge